services:
  web:
    build: .
    platform: linux/arm64
    ports:
      - "18088:80"
    volumes:
      - ./uploads:/var/www/html/Uploads
    environment:
      - DB_HOST=db:3306
      - DB_NAME=xxjz
      - DB_USER=xxjz
      - DB_PWD=5Qk9B8uvaRMcfLfpN
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=G4xMQ8gBX8v7xb%xvH
      - MYSQL_DATABASE=xxjz
      - MYSQL_USER=xxjz
      - MYSQL_PASSWORD=5Qk9B8uvaRMcfLfpN

networks:
  default:
    driver: bridge

volumes:
  mysql_data: 
